server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/acgmanhua?serverTimeZone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 2000
      minimum-idle: 5
      maximum-pool-size: 12
      idle-timeout: 30000
      max-lifetime: 1200000
      auto-commit: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        id.new_generator_mappings: false
        format_sql: true
  redis:
    database: 0
    host: 192.168.226.131
    port: 6379
    password: redispass


  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:/templates/

  mail:
    host: smtp.163.com
    username: normalworld@163.com
    password: caobidan
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true

  activemq:
    broker-url: tcp://192.168.226.131:61616
    in-memory: true
    pool:
      enabled: false
    packages:
      trust-all: true

  data:
    mongodb:
      uri: mongodb://192.168.226.131:27017/local

logging:
  config: classpath:log4j2.xml

mybatis:
  mapper-locations: classpath:/mappers/*Mapper.xml
  type-aliases-package: com.example.dao

management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
